micronaut:
  application:
    name: keyManagerRest
grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: '${GRPC_HOST:localhost}:${GRPC_PORT:50051}'
      keepAliveWithoutCalls: true